// Generated by https://quicktype.io

export default interface Pet {
    _id: string
    name: string
    dob?: Date
    species?: string
    gender?: string
    filename?: string
    kids_comp?: boolean
    pets_comp?: boolean
    description?: string
    last_modified?: string
}
