// Generated by https://quicktype.io

export default interface IPet {
    _id: string
    name: string
    dob?: Date
    species?: string
    gender?: string
    filename?: string
    spay_neut?: boolean
    vaxxed?: boolean
    description?: string
    last_modified?: string
}
